### ISSUE TITLE
Runtime Errors

### ISSUE THREAD

**Issue by mdombro** [jeffaco/duplicacy-util#7] opened 2018-08-10 23:03 UTC
Hello,

Hate to open another issue, but just last night I ran into an error after executing the program. I had just finished backing up both to a local NAS box and then copying that backup to the cloud service Wasabi. So, to clarify, there was no new data for duplicacy-util to work on, I just wanted to run it to see if any errors would come up. 

It seemed to go over the local NAS data fine, however the issue occurred when it worked on copying to wasabi. Below is the error:

```E:\Backup_repo\Duplicacy>duplicacy-util_win_x64_1.2.exe -f backup -a
21:34:01 Using global config: C:\Users\mdombro\.duplicacy-util\duplicacy-util.yml
21:34:01 Using config file:   C:\Users\mdombro\.duplicacy-util\backup.yml
21:34:01 duplicacy-util starting, version: 1.2, Git Hash: 4aa94bc
21:34:01 Rotating log files
21:34:01 Beginning backup on 08-09-2018 21:34:01
21:34:01 Backing up to storage nas with 10 threads
21:34:02   Files: 1530 total, 8,548M bytes; 1 new, 863 bytes
21:34:02   All chunks: 1762 total, 8,549M bytes; 4 new, 627K bytes, 266K bytes uploaded
21:34:02   Duration: 1 second
21:34:02 Backing up to storage wasabi with 5 threads
21:34:03   Files: 1530 total, 8,548M bytes; 1 new, 863 bytes
21:34:03   All chunks: 1762 total, 8,549M bytes; 4 new, 627K bytes, 266K bytes uploaded
21:34:03   Duration: 1 second
21:34:03 Copying from storage nas to storage wasabi with 10 threads
21:34:04   Duration: 1 second
21:34:04 Pruning storage wasabi
21:34:04 Checking storage wasabi
panic: runtime error: index out of range

goroutine 1 [running]:
main.performBackup(0xc000000018, 0x896880)
        /Users/jeff/local/go/src/duplicacy-util/duplicacy-util.go:498 +0x2eb8
main.obtainLock(0x0)
        /Users/jeff/local/go/src/duplicacy-util/duplicacy-util.go:323 +0x278
main.processArguments(0x0, 0x0)
        /Users/jeff/local/go/src/duplicacy-util/duplicacy-util.go:296 +0x662
main.main()
        /Users/jeff/local/go/src/duplicacy-util/duplicacy-util.go:160 +0x98
```

My backup.yaml configuration file is as such:
```
repository: E:\Backup_repo
storage:
    1:
        name: nas
        threads: 10
    2:
        name: wasabi
        threads: 5

copy:
    1:
        from: nas
        to: wasabi
        threads: 10
        
prune:
    1:
        storage: nas
        keep: "0:365 30:180 7:30 1:7"
    
    1:
        storage: wasabi
        keep: "0:365 30:180 7:30 1:7"
        
check:
    1:
        storage: nas
        all: true
    2:
        storage: wasabi
        all: true
```
I also just re-ran it tonight and got a different error:
```E:\Backup_repo\Duplicacy>duplicacy-util_win_x64_1.2.exe -f backup -a -v
19:00:55 Using global config: C:\Users\user\.duplicacy-util\duplicacy-util.yml
19:00:55 Using config file:   C:\Users\user\.duplicacy-util\backup.yml
19:00:55
19:00:55 Backup Information:
19:00:55   Num  Storage             Threads
19:00:55    1   nas                    10
19:00:55    2   wasabi                 5
19:00:55 Copy Information:
19:00:55   Num  From                To                  Threads
19:00:55    1   nas                 wasabi                 10
19:00:55
19:00:55 Prune Information:
19:00:55    1: Storage wasabi
      Keep: -keep 0:365 -keep 30:180 -keep 7:30 -keep 1:7
19:00:55
19:00:55 Check Information:
19:00:55   Num  Storage             All Snapshots
19:00:55    1   nas                     true
19:00:55    2   wasabi                  true
19:00:55
19:00:55 duplicacy-util starting, version: 1.2, Git Hash: 4aa94bc
19:00:55 Rotating log files
19:00:55 Beginning backup on 08-10-2018 19:00:55
19:00:55 Backing up to storage nas with 10 threads
Error executing command: exit status 100```

Any pointers of things to try would be super appreciated!

**Comment by jeffaco** [comment] 2018-08-10 23:39
Okay, there are two problems here:

1. `panic: runtime error: index out of range`, and
2. `Error executing command: exit status 100`

So sorry! The first problem is actually a bug. There is a typo in the code, and due to that, there is an assumption that the number of repositories to prune and the number of repositories to check are the same. This is actually a bug, and I have a fix for that. However, that was exposed due to a bug in your `backup.yaml` file. You essentially have 1 prune repository because both tags start with 1. My code will dutifully replace the second entry with the first entry (which is why only `wasabi` was listed as a storage to prune).

For the second problem, can you please run `duplicacy-util` in debug mode (include `-d`), and replicate the error executing command. With the debug output, I should be able to understand what's happening. Thanks!

**Comment by jeffaco** [comment] 2018-08-10 23:49
First problem resolved with git commit b11e660.

Pushed to master, but not yet bundled in a release. I consider this a minor problem since it's only exposed due to a bug in the backup configuration file, but I'm happy to make a new release if @mdombro considers this urgent.

**Comment by jeffaco** [comment] 2018-08-12 21:02
Hmph. All I can see here is that Windows is having some sort of problem executing `duplicacy.exe`.

Note that, due to your configuration, `duplicacy.exe` is supposed to be in your backup respository, at file `E:\Backup_repo\Duplicacy\duplicacy.exe`. Does this file actually exist? Can you execute that with the -help qualifier? (The rest of the output is dumping the arguments array, I'm passing `backup`, `-stoprage nas`, `-threads 10`, and `-stats`.)

Please verify that the executable exists at that location, and that you can run it with -help. Thanks. If it does not exist there, point to it via the global configuration file, or put it on your PATH.

Let me know, thanks!

**Comment by boedy** [comment] 2018-08-16 10:32
@jeffaco 

I'm on Mac OS and I'm getting the same exit status code 100. I did not build from source, but downloaded the 1.2 release from github. I've put it in my /usr/local/bin directory. Initialising the repository through `duplicacy init -e -storage-name b2 air-home b2://<my bucket>` is the only step I did before running `duplicacy-util -f air-home -a -d`

```
12:26:03 Using config file:   /Users/boedy/.duplicacy-util/air-home.yml
12:26:03
12:26:03 Backup Information:
12:26:03   Num	Storage             Threads
12:26:03    1	b2                     1
12:26:03
12:26:03 Prune Information:
12:26:03    1: Storage b2
      Keep: -keep 0:365 -keep 30:180 -keep 7:30 -keep 1:7
12:26:03
12:26:03 Check Information:
12:26:03   Num	Storage             All Snapshots
12:26:03    1	b2                      false
12:26:03
12:26:03
12:26:03 Backup Info: [map[vss:false name:b2 threads:1]]
12:26:03 Copy Info: []
12:26:03 Prune Info: [map[storage:b2 keep:-keep 0:365 -keep 30:180 -keep 7:30 -keep 1:7]]
12:26:03 Check Info[map[storage:b2 all:false]]
12:26:03 duplicacy-util starting, version: 1.2, Git Hash: 4aa94bc
12:26:03 Rotating log files
12:26:03 Beginning backup on 08-16-2018 12:26:03
12:26:03 Backing up to storage b2 with 1 threads
12:26:03 Executing: duplicacy[backup -storage b2 -threads 1 -stats]
Error executing command: exit status 100
```

**Comment by jeffaco** [comment] 2018-08-16 15:04
I believe that the root cause of this is identical to the error reported by @mdombro , although the errors are ever so lightly different.

In this case:

```
12:26:03 Executing: duplicacy[backup -storage b2 -threads 1 -stats]
```

There is no path to `duplicacy`, as defined in the global configuration file. As a result, Go's [os/exec](https://golang.org/pkg/os/exec/) package will look for `duplicacy` on the default path. Depending on where you put it, and if you modified the system default path, that can make it impossible for the Go language to find the executable. I'm tempted to modify the code to use [LookPath](https://golang.org/pkg/os/exec/#LookPath) just to print an error before hand if I know `duplicacy` probably won't be able to be executed. While that won't fix this, it will help to diagnose it with a meaningful error message.

@boedy For now, please modify your global configuration file and add `duplicacypath` to it, carefully giving the absolute (complete) path to `duplicacy`. Then run `duplicacy-util` again with `-d` and see if it works. See [duplicacy-util README.md](https://github.com/jeffaco/duplicacy-util#global-configuration-file) for details on this.

Let me know if this helps, thanks!

[Note that I'm leaving for a four day camping trip; I may not be able to answer until Sunday when I return, sorry in advance for any delay.]

**Comment by jeffaco** [comment] 2018-08-21 06:33
I will definitely be adding a "getting started" section to the README.md, and I'll be sure to point out this issue there. Thanks @boedy for pointing this out!

I've also modified duplicacy-util in commit hash b76eb97 to make this easier to identify. With this change, a password problem will result in the following output:

```
23:29:32 Rotating log files
23:29:32 Beginning backup on 08-20-2018 23:29:32
23:29:32 Backing up to storage b2 with 10 threads
23:29:33   Error: Duplicacy appears to be prompting for a password
23:29:33   Enter Backblaze Account ID:Enter Backblaze Application Key:Failed to load the Backblaze B2 storage at b2://quickendb: Authorization failure
Error executing command: exit status 100
```

The log file will have similar output there.

@boedy Do you still have the log file where you encountered this error? In your log file where this occurred, did this also end with `Authorization failure`? Without looking at duplicacy source code, I'm not 100% sure if `duplicacy` will use this error with all backends or just with Backblaze.

**Comment by boedy** [comment] 2018-08-23 10:12
@jeffaco 

My log output:
```
18:52:41 Beginning backup on 08-16-2018 18:52:41
18:52:41 ######################################################################
18:52:41 Backing up to storage b2 with 1 threads
18:52:41 Executing: /usr/local/bin/duplicacy[backup -storage b2 -threads 1 -stats]
18:52:41 Storage set to b2://boedy-macbook-air
18:52:52 Enter storage password:Failed to read the password: EOF
18:52:52 Error executing command: exit status 100
```

**Comment by jeffaco** [comment] 2018-08-23 15:56
Perfect, @boedy, thanks! Naturally, your situation is slightly different than mine. I'll be sure to add your case to the code base (with a unit test), and will close this issue when done.

**Comment by jeffaco** [comment] 2018-08-27 00:11
@boedy Fixed your case of no password (`Enter storage password:`) in commit hash 08b8c63. Resolving this issue; thanks for the feedback!

**Closed by jeffaco** 2018-08-27 00:11 UTC
